name: medella_new
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  get: 4.6.5
  get_storage: ^2.0.3
  get_it: ^7.2.0
  flutter_svg: ^1.1.1+1
  dio: ^4.0.6
  pinput: ^2.2.11
  intl: ^0.17.0
  firebase_auth: ^3.5.1
  firebase_core: ^1.20.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/flags/